### PR TITLE
Typo

### PR DESCRIPTION
**Pull request by lifeout**
Some typos.

### CODE REVIEW

**Comment by hemanth** [comment]
Thanks. `NONE_PATH` sounds cool though :wink:

**Comment by lifeout** [comment]
Found another issue actually... Please take a look:

```code
[Info]
  NONE_PATH = /usr/lib/nodejs:/usr/lib/node_modules:/usr/share/javascript:/usr/lib/nodejs:/usr/lib/node_modules:/usr/share/javascript
  npm root  = /home/myusername/local/lib/node_modules

[Fix] Append the npm root value to your NODE_PATH variable
Add this line to your .bashrc
    export NODE_PATH=$NODE_PATH:/usr/lib/nodejs:/usr/lib/node_modules:/usr/share/javascript:/usr/lib/nodejs:/usr/lib/node_modules:/usr/share/javascript
  Or run this command
    echo "export NODE_PATH=$NODE_PATH:/usr/lib/nodejs:/usr/lib/node_modules:/usr/share/javascript:/usr/lib/nodejs:/usr/lib/node_modules:/usr/share/javascript" >> ~/.bashrc && source ~/.bashrc

```

As far as I understand doctor tries to suggest a solution - but the paths he suggests to add to NODE_PATH are not quite right - I've managed to fix my own problem by adding the npm root to NODE_PATH manually. I'm pretty sure paths and things on my machine is a big big mess, but doctor can have an issues as well.

**Comment by hemanth** [comment]
//cc @SBoudrias ^

**Comment by SBoudrias** [comment]
Fixed here: https://github.com/yeoman/doctor/commit/504b91a25f2af239a5c86ac66d29dfd479a6d7af

Next time please open a new issue so we can keep tracks of our bugs.

**Comment by hemanth** [comment]
:+1:

**Pull request merged**
